{
 "title": "Default",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Hash Rate - Gh/s [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "avg_over_time(hash_rate[5m])", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Shares Rejected %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(rate(shares_rejected[20m]) / (rate(shares_accepted[20m]) + rate(shares_rejected[20m]))) * 100\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Hash Rate / Expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(hash_rate[20m]) / avg_over_time(expected_hash_rate[20m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Power - Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(power)", "legendFormat": "__auto" },
    { "expr": "power", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Temp - Celsius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "asic_temperature_celsius", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}